config/routes.rb
KwTraining::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    resources :specialities
    resources :users do
      collection do
        get 'user_report'
      end
    end
    resources :columnists do
      resources :articles
    end
    resources :categories
    resources :organizations do
      resources :organization_images
    end
    resources :highlights
    resources :customers
    resources :enterprises do
      resources :portfolios

    end
    resources :statics, only: [:index]
    resources :tags
    resources :wikis
    resources :suggestions
    resources :enterprise_rates

    root to: 'statics#index'
  end

  resources :password_reset
  resources :user_sessions
  resources :users do
    collection do
      post 'search_cep'
    end
  end
  resources :searchs
  resources :profiles
  resources :comments do
    member do
      get :deletar
    end
  end
  resources :likes
  resources :blogs
  resources :categorias
  resources :suggestions
  resources :wiki
  resources :eventos
  resources :empresas do
    resources :rates
    member do
      get :tags
      get :filters
    end
  end

  resources :terms
  resources :sobre
  resources :colunas do
    resources :artigos
  end

  resources :homes do
    collection do
      get :register
    end
  end

  resources :new_enterprises
  resources :contacts
  resources :cadastro_empresas

  resources :authentications
  match '/auth/:provider/callback', to: 'authentications#create', via: :all

  root to: 'homes#index'

  match 'blog', to: "blogs#index", via: :all
  match 'caixa-de-ideias', to: "suggestions#new", via: :all
  match 'perfil', to: "profiles#index", via: :all
  match 'register', to: "homes#register", via: :all
  match 'login', to: 'user_sessions#new', via: :all
  match 'logout', to: 'user_sessions#destroy', via: :all
  get "/cities_by_state" => "cities#cities_by_state"
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_and_belongs_to_many :enterprises, class_name: 'Admin::Enterprise'
end

app/controllers/admin/wikis_controller.rb
class Admin::WikisController < ApplicationController
  access_control do
    allow :administrator, :all
  end
  layout "admin"

  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @wikis = Wiki.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @wiki = Wiki.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.save
    respond_to do |format|
      if @wiki.save
        format.html { redirect_to admin_wiki_path(@wiki), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: adminwiki_path(@wiki) }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to admin_wiki_path(@wiki), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @wiki] }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to admin_wikis_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title,:description,:active, :published, :speciality_related, enterprise_ids: [])
    end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  def index
    #CArrega todos os termos que comecem com numero

  end

  def show
    @wikis = Wiki.where(["title LIKE ? AND published = 1", "#{params[:id]}%"])
    if params[:id] == '1'
      @wikis = Wiki.where(["title regexp '^[0-9]+' AND published = 1"])
    end

    puts "WIKI===================#{@wikis.inspect}"
  end
end

app/helpers/admin/wikis_helper.rb
module Admin::WikisHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/admin/wikis/_form.html.haml
= form_for [:admin, @wiki] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      Confira os campos marcados em vermelho.
  .box-body
    .form-group
      = f.label :title
      = f.text_field :title, :class => "form-control", :placeholder => "titulo"
    .form-group
      = f.label :description
      = f.text_area :description, :class => "form-control ckeditor", :placeholder => "descrição"

    .form-group
      = f.label :speciality_related, "Produto relacionado"
      %br
      = f.collection_select(:speciality_related, Speciality.all, :name, :name, { :include_blank => 'Selecione o produto relacionado' }, {class: "form-control enterprise_state select2"})

    / .form-group
    /   = f.label :enterprise_ids, "Empresas relacionadas"
    /   %br
    /   = f.collection_check_boxes(:enterprise_ids, Admin::Enterprise.all, :id, :name)

    .form-group
      = f.label :published
      = f.check_box :published
    .box-footer
    =f.submit nil, :class => "btn btn-primary"

app/views/admin/wikis/edit.html.haml
%section.content-header
  %h1
    Artigos
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Artigos


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Editar Artigo
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_wikis_path, :class => "btn btn-default"
        = link_to t("show"), admin_wiki_path(@wiki), :class => "btn btn-default"

app/views/admin/wikis/index.html.haml
%section.content-header
  %h1
    Wiki
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "/admin"}
        %i.fa.fa-dashboard
        Home
    %li.active Wiki
/ Main content
%section.content
  .col-xs-12
    %p
      = link_to "Novo Wiki", new_admin_wiki_path, :class => "btn btn-primary" 
      / = link_to "Ver Todos", admin_articles_path, :class => "btn btn-primary"  if !params[:tag].blank?
    
    .box
      .box-header
        %h3.box-title 
          Artigos Cadastrados 
          
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th="Título"
            %th="Publicado?"
            %th=t("actions")
          - for wiki in @wikis 
            %tr
              %td= wiki.title 
              %td= wiki.published              
              %td 
                = link_to t("show"), admin_wiki_path(wiki), :class => "btn btn-default"
                = link_to t("edit"), edit_admin_wiki_path(wiki), :class => "btn btn-default"
                = link_to 'Destroy', admin_wiki_path(wiki), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-default"

    %p
      = link_to "Novo Artigo", new_admin_wiki_path, :class => "btn btn-primary" 
      / = link_to "Ver Todos", admin_articles_path, :class => "btn btn-primary"  if !params[:tag].blank?

app/views/admin/wikis/new.html.haml
%section.content-header
  %h1
    Artigo
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Artigo


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title Novo Artigo
        / /.box-header
        / form start
        = render 'form'
      

      %p
        = link_to t("back_list"), admin_wikis_path, :class => "btn btn-default"

app/views/admin/wikis/show.html.haml
%section.content-header
  %h1
    Artigos
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Home
    %li.active Artigos
     

/ Main content
%section.content   
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title="#{@wiki.title}"  
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.description")}:"
            %br
            = raw @wiki.description   
        .box-body  
          %p
            %b= "#{t("activerecord.attributes.article.published")}: "
            = @wiki.published
        
  = link_to t("back_list"), admin_wikis_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_wiki_path(@wiki), :class => "btn btn-default" 
  = link_to "Novo Artigo", new_admin_wiki_path, :class => "btn btn-primary"